[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/leaderboard"
  to = "/.netlify/functions/leaderboard"
  status = 200

[[redirects]]
  from = "/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/save-note"
  to = "/.netlify/functions/save-note"
  status = 200

[[redirects]]
  from = "/supporter"
  to = "/.netlify/functions/supporter"
  status = 200

[[redirects]]
  from = "/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
